# Generated by Django 3.2.15 on 2022-08-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.TextField(),
        ),
    ]
